"""store port info

Revision ID: a711f41da52f
Revises: 662697a62fa1
Create Date: 2020-11-08 14:44:54.263084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a711f41da52f'
down_revision = '662697a62fa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_process_time', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('used_port', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'used_port')
    op.drop_column('users', 'last_process_time')
    # ### end Alembic commands ###
